version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/nftattoo
    ports:
      - "3000:3000"
    depends_on:
      - db

#version: '3.3'
#services:
#  db:
#    image: postgres
#    env_file:
#      - .env
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - db_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#  web:
#    build: .
#    command: bundle exec rails s -e development -p 3000 -b '0.0.0.0'
#    volumes:
#    - .:/nftattoo
#    - gem_cache:/usr/local/bundle/gems
#    - node_modules:/nftattoo/node_modules
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
#volumes:
#  gem_cache:
#  db_data:
#  node_modules:
#
#